#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely.

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
done
