#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.

while IFS=":" read -r USER PASSWD U_ID G_ID UID_INFO HOME_DIR SHELL
do
    echo "The user $USER is part of the $G_ID gang, lives in $HOME_DIR and rides $SHELL. $U_ID's place is protected by the passcode $PASSWD, more info about the user here: $UID_INFO"
done < /etc/passwd
