#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20,
# "bad luck from China" for the 4th loop iteration
# "bad luck from Japan" for the 9th loop iteration
# "bad luck from Italy" for the 17th loop iteration

i=1
while [[ "$i" -le 20 ]]
do
	case "$i" in
	    4)	echo "bad luck from China"
	     	;;&
	    9) echo "bad luck from Japan"
	       ;;&
	    17) echo "bad luck from Italy"
	     	 ;;&
	     *) 	echo "$i"
	esac
	i=$((i+1))
done
