#!/usr/bin/env bash
# This script display The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

LIST="$(ls)"
for i in $LIST
do
    find "$i" | cut -d - -f2
done
