#!/usr/bin/env bash
# Script configures an Ubuntu server with localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.new
echo -e "localhost\t127.0.0.2\nfacebook\t8.8.8.8" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
